//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSDate, NSDictionary, NSString, NSUUID;

@interface LSPlugInKitProxy : NSObejct//LSBundleProxy <NSSecureCoding>
{
    NSDictionary *_infoPlist;
    LSBundleProxy *_parentBundle;
    unsigned int _parentBundleID;
    _Bool _isOnSystemPartition;
    NSString *_pluginIdentifier;
    NSString *_protocol;
    NSUUID *_pluginUUID;
    NSDictionary *_pluginKitDictionary;
    NSDate *_registrationDate;
}

+ (_Bool)supportsSecureCoding;
+ (id)plugInKitProxyForUUID:(id)arg1 bundleIdentifier:(id)arg2 pluginIdentifier:(id)arg3 version:(id)arg4 bundleURL:(id)arg5;
+ (id)pluginKitProxyForURL:(id)arg1;
+ (id)pluginKitProxyForIdentifier:(id)arg1;
+ (id)pluginKitProxyForUUID:(id)arg1;
+ (id)plugInKitProxyForPlugin:(unsigned int)arg1;
@property(readonly, nonatomic) _Bool isOnSystemPartition; // @synthesize isOnSystemPartition=_isOnSystemPartition;
@property(readonly, nonatomic) NSDate *registrationDate; // @synthesize registrationDate=_registrationDate;
@property(readonly, nonatomic) NSDictionary *pluginKitDictionary; // @synthesize pluginKitDictionary=_pluginKitDictionary;
@property(readonly, nonatomic) NSUUID *pluginUUID; // @synthesize pluginUUID=_pluginUUID;
@property(readonly, nonatomic) NSString *protocol; // @synthesize protocol=_protocol;
@property(readonly, nonatomic) NSString *pluginIdentifier; // @synthesize pluginIdentifier=_pluginIdentifier;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)iconDataForVariant:(int)arg1;
- (id)appStoreReceiptURL;
- (id)localizedShortName;
- (id)localizedName;
@property(readonly, nonatomic) LSBundleProxy *containingBundle;
@property(readonly, nonatomic) NSDictionary *infoPlist;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)_initWithUUID:(id)arg1 bundleIdentifier:(id)arg2 pluginIdentifier:(id)arg3 version:(id)arg4 bundleURL:(id)arg5;
- (id)_initWithPlugin:(unsigned int)arg1;

@end

