//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class LSApplicationProxy, NSArray, NSDictionary, NSString, NSURL;

@interface LSResourceProxy : NSObject
{
    NSString *_localizedName;
    NSString *_boundApplicationIdentifier;
    NSURL *_boundContainerURL;
    NSURL *_boundDataContainerURL;
    NSURL *_boundResourcesDirURL;
    NSDictionary *_boundIconsDictionary;
    NSString *_boundIconCacheKey;
    NSArray *_boundIconFileNames;
    LSApplicationProxy *_typeOwner;
    _Bool _boundIconIsPrerendered;
    _Bool _boundIconIsBadge;
}

@property(strong, nonatomic) NSString *localizedName; // @synthesize localizedName=_localizedName;
- (id)iconStyleDomain;
- (id)iconDataForVariant:(int)arg1;
- (id)iconDataForStyle:(id)arg1 width:(long long)arg2 height:(long long)arg3 options:(unsigned long long)arg4;
- (void)setBoundIconIsBadge:(_Bool)arg1;
@property(readonly, nonatomic) _Bool boundIconIsBadge;
- (void)setBoundIconIsPrerendered:(_Bool)arg1;
- (_Bool)boundIconIsPrerendered;
- (void)setTypeOwner:(id)arg1;
- (id)typeOwner;
- (void)setBoundIconFileNames:(id)arg1;
- (id)boundIconFileNames;
- (void)setBoundIconCacheKey:(id)arg1;
- (id)boundIconCacheKey;
- (void)setBoundIconsDictionary:(id)arg1;
@property(readonly, nonatomic) NSDictionary *iconsDictionary;
- (id)boundIconsDictionary;
- (void)setBoundResourcesDirectoryURL:(id)arg1;
- (id)boundResourcesDirectoryURL;
- (void)setBoundDataContainerURL:(id)arg1;
- (id)boundDataContainerURL;
- (void)setBoundContainerURL:(id)arg1;
- (id)boundContainerURL;
- (void)setBoundApplicationIdentifier:(id)arg1;
- (id)boundApplicationIdentifier;
- (void)setLocalizedName:(id)arg1;
- (void)dealloc;
- (id)_initWithLocalizedName:(id)arg1;
- (id)_initWithLocalizedName:(id)arg1 boundApplicationIdentifier:(id)arg2 boundContainerURL:(id)arg3 dataContainerURL:(id)arg4 boundResourcesDirectoryURL:(id)arg5 boundIconsDictionary:(id)arg6 boundIconCacheKey:(id)arg7 boundIconFileNames:(id)arg8 typeOwner:(id)arg9 boundIconIsPrerendered:(_Bool)arg10 boundIconIsBadge:(_Bool)arg11;

@end

