/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:44:45 AM Eastern European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuartzCore/QuartzCore.h>
@class NSArray;

@interface CAWindowServer : NSObject {

//	CAWindowServerImpl* _impl;

}

@property (readonly) NSArray * displays; 
@property (getter=isMirroringEnabled) BOOL mirroringEnabled; 
@property (assign) unsigned rendererFlags; 
+(id)serverIfRunning;
+(id)server;
+(id)contextWithOptions:(id)arg1 ;
+(id)context;
-(void)addDisplay:(id)arg1 ;
-(void)removeDisplay:(id)arg1 ;
-(void)removeAllDisplays;
-(id)displayWithName:(id)arg1 ;
-(id)displayWithDisplayId:(unsigned)arg1 ;
-(id)displayWithUniqueId:(id)arg1 ;
-(void)_detectDisplays;
-(void)setMirroringEnabled:(BOOL)arg1 ;
-(BOOL)isMirroringEnabled;
-(unsigned)rendererFlags;
-(void)dealloc;
-(id)init;
-(id)description;
-(id)_init;
-(void)setRendererFlags:(unsigned)arg1 ;
-(NSArray *)displays;
@end

